### ISSUE TITLE
Drop support for Ruby versions prior to 2.3

### ISSUE THREAD

**Issue by jufemaiz** [jufemaiz/aemo#34]
Lonely operator support was introduced to Ruby in 2.3.

Ruby 2.2.8 is currently at EOL support with stable releases at 2.3.5 and 2.4.2 (with 2.5.0-preview1 available for review). Src: https://www.ruby-lang.org/en/downloads/

If there is no opposition to dropping 2.2.8 support I will be dropping support by EOY.

**Comment by jufemaiz** [comment]
Ping @sjauld

**Comment by sjauld** [comment]
+1

**Comment by sjauld** [comment]
v0.3 milestone?
